openapi: 3.1.0
info:
  title: Food Order System API
  description: API for managing customers, items, and orders in the Food Order System.
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: Customers
    description: Operations related to customers
  - name: Items
    description: Operations related to menu items
  - name: Orders
    description: Operations related to customer orders

paths:
  /api/v1/customers:
    get:
      tags:
        - Customers
      summary: Get all customers
      operationId: getAllCustomers
      responses:
        '200':
          description: A list of all customers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerListResponseDto'
    post:
      tags:
        - Customers
      summary: Create a new customer
      operationId: createCustomer
      requestBody:
        description: Customer object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequestDto'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

  /api/v1/customers/{customerId}:
    get:
      tags:
        - Customers
      summary: Get customer by ID
      operationId: getCustomerById
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponseDto'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Customers
      summary: Delete customer by ID
      operationId: deleteCustomerById
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '204':
          description: Customer deleted successfully
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/items:
    get:
      tags:
        - Items
      summary: Get all items
      operationId: getAllItems
      responses:
        '200':
          description: A list of all items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemListResponseDto'
    post:
      tags:
        - Items
      summary: Create a new item
      operationId: createItem
      requestBody:
        description: Item object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequestDto'
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
    put:
      tags:
        - Items
      summary: Update an existing item
      operationId: updateItem
      requestBody:
        description: Item object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemUpdateRequestDto'
      responses:
        '200':
          description: Item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/items/{itemId}:
    get:
      tags:
        - Items
      summary: Get item by ID
      operationId: getItemById
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemResponseDto'
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Items
      summary: Delete item by ID
      operationId: deleteItemById
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '204':
          description: Item deleted successfully
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/orders:
    get:
      tags:
        - Orders
      summary: Get all orders
      operationId: getAllOrders
      responses:
        '200':
          description: A list of all orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponseDto'
    post:
      tags:
        - Orders
      summary: Create a new order
      operationId: createOrder
      requestBody:
        description: Order object that needs to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequestDto'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: Customer or Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Get order by ID
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Orders
      summary: Delete order by ID
      operationId: deleteOrderById
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '204':
          description: Order deleted successfully
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/orders/by-customer/{customerId}:
    get:
      tags:
        - Orders
      summary: Get all orders for a specific customer
      operationId: getOrdersByCustomerId
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        '200':
          description: A list of orders for the customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponseDto'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/orders/add-item:
    patch:
      tags:
        - Orders
      summary: Add an item to an existing order
      operationId: addItemToOrder
      requestBody:
        description: Details of the item to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManageOrderItemRequestDto'
      responses:
        '200':
          description: Item added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: Order or Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/orders/remove-item:
    patch:
      tags:
        - Orders
      summary: Remove an item from an existing order
      operationId: removeItemFromOrder
      requestBody:
        description: Details of the item to remove
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManageOrderItemRequestDto'
      responses:
        '200':
          description: Item removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: Order or Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UUID:
      type: string
      format: uuid
      description: Universally Unique Identifier
      example: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11

    # Customer Schemas
    CustomerRequestDto:
      type: object
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 20
          example: John
        lastName:
          type: string
          minLength: 2
          maxLength: 20
          example: Doe
      required:
        - firstName
        - lastName
    CustomerResponseDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
    CustomerListResponseDto:
      type: object
      properties:
        customers:
          type: array
          items:
            $ref: '#/components/schemas/CustomerResponseDto'

    # Item Schemas
    ItemRequestDto:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 20
          example: Pizza
        description:
          type: string
          minLength: 10
          example: Delicious cheese pizza
        price:
          type: number
          format: double
          minimum: 0.01
          example: 12.99
      required:
        - name
        - description
        - price
    ItemUpdateRequestDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        description:
          type: string
          minLength: 10
          example: An updated description
        price:
          type: number
          format: double
          minimum: 0.01
          example: 13.99
      required:
        - id
    ItemResponseDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
          example: Pizza
        description:
          type: string
          example: Delicious cheese pizza
        price:
          type: number
          format: double
          example: 12.99
    ItemListResponseDto:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemResponseDto'

    # Order Schemas
    OrderItemRequestDto:
      type: object
      properties:
        itemId:
          $ref: '#/components/schemas/UUID'
        quantity:
          type: integer
          format: int32
          minimum: 1
          example: 2
      required:
        - itemId
        - quantity
    OrderRequestDto:
      type: object
      properties:
        customerId:
          $ref: '#/components/schemas/UUID'
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemRequestDto'
          minItems: 1
      required:
        - customerId
        - orderItems
    ManageOrderItemRequestDto:
      type: object
      properties:
        orderId:
          $ref: '#/components/schemas/UUID'
        itemId:
          $ref: '#/components/schemas/UUID'
        quantity:
          type: integer
          format: int32
          minimum: 1
          example: 1
      required:
        - orderId
        - itemId
        - quantity
    OrderItemResponseDto:
      type: object
      properties:
        itemId:
          $ref: '#/components/schemas/UUID'
        quantity:
          type: integer
          format: int32
          example: 2
    OrderResponseDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        customerId:
          $ref: '#/components/schemas/UUID'
        totalPrice:
          type: number
          format: double
          example: 25.98
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponseDto'
    OrderListResponseDto:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponseDto'

    # Error Schemas (based on GlobalExceptionHandler)
    ErrorResponse:
      type: object
      description: Standard error response based on RFC 7807 Problem Details
      properties:
        type:
          type: string
          example: urn:problem-type:resource-not-found
        title:
          type: string
          example: Resource Not Found
        status:
          type: integer
          format: int32
          example: 404
        detail:
          type: string
          example: Customer with id [uuid] not found
    ParamsValidationDetails:
      type: object
      description: Details of a single validation error
      properties:
        field:
          type: string
          example: firstName
        message:
          type: string
          example: is required
    ValidationErrorResponse:
      type: object
      description: Validation error response based on RFC 7807 Problem Details
      properties:
        type:
          type: string
          example: urn:problem-type:validation-error
        title:
          type: string
          example: Validation Error
        status:
          type: integer
          format: int32
          example: 400
        detail:
          type: string
          example: Request Validation Failed
        validationDetails:
          type: array
          items:
            $ref: '#/components/schemas/ParamsValidationDetails'